### ISSUE TITLE
Solution doesn't compile

### ISSUE THREAD

**Issue by Sambafrosch** [grantcolley/authorisationmanager#1]
Hi,
Just cloned authorationmanager and tried to compile. Got these compilation errors:
The type or namespacename 'EntityBase' could not be found (Are you missing a using directive oder an assembly reference?) 
Following the original error messages (sorry, only in german, but with line and file name information)
Der Typ- oder Namespacename 'EntityBase' konnte nicht gefunden werden. (Fehlt eine Using-Direktive oder ein Assemblyverweis?) (CS0246) - C:\Users\jst\Documents\SharpDevelop\GrantColley\authorisationmanager\UI\WPF\Model\NodeEntityBase.cs:5,44
Der Typ- oder Namespacename 'EntityBase' konnte nicht gefunden werden. (Fehlt eine Using-Direktive oder ein Assemblyverweis?) (CS0246) - C:\Users\jst\Documents\SharpDevelop\GrantColley\authorisationmanager\UI\WPF\ViewModel\ConfigurationAuthorisationViewModel.cs:17,17
Der Typ- oder Namespacename 'EntityBase' konnte nicht gefunden werden. (Fehlt eine Using-Direktive oder ein Assemblyverweis?) (CS0246) - C:\Users\jst\Documents\SharpDevelop\GrantColley\authorisationmanager\UI\WPF\ViewModel\ConfigurationAuthorisationViewModel.cs:58,16

**Comment by grantcolley** [comment]
Hi Stephan,

The authorisationmanager solution is very much "work in progress" and still several weeks from completion. The solution currently references the following projects which you will need to clone in order for it to compile:
- DevelopmentInProgress.AuthorisationManager.Data
- DevelopmentInProgress.AuthorisationManager.Data.SQLServer
- DevelopmentInProgress.AuthorisationManager.Service
- DevelopmentInProgress.AuthorisationManager.Service.Test
- DevelopmentInProgress.AuthorisationManager.WPF
- DevelopmentInProgress.DipCore
- DevelopmentInProgress.DipSecure
- DevelopmentInProgress.Origin
- DevelopmentInProgress.WPFControls

Note, you will need to set Origin as the StartUp project in the solution as it is the WPF shell. Also, projects Origin, WPFControls, DipSecure and DipCore are complete in their own right.

When I have completed authorisationmanager the solution will still require a reference to Origin (as it is the StartUp project), but will reference WPFControls, DipSecure and DipCore as dll's which will be available as nuget packages.

Let me know if you need anymore assistance.

Regards,
Grant
